import type { PageConfig, SpreadPhotoLayout } from "../lib/types";
import { COLOR_BLUE, createPageAnnotation } from "../lib/typography";

const pile: SpreadPhotoLayout[] = [
  {
    file: "resources/虾片/ming.png",
    x: 312,
    y: 830,
    w: 120,
    rot: 21,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 130,
    y: 830,
    w: 120,
    rot: 171,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 432,
    y: 830,
    w: 120,
    rot: 209,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 570,
    y: 830,
    w: 120,
    rot: 90,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 223,
    y: 750,
    w: 120,
    rot: 351,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 501,
    y: 731,
    w: 120,
    rot: 303,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 381,
    y: 721,
    w: 120,
    rot: 242,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 711,
    w: 120,
    rot: 56,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 295,
    y: 638,
    w: 120,
    rot: 113,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 570,
    y: 633,
    w: 120,
    rot: 176,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 450,
    y: 622,
    w: 120,
    rot: 231,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 177,
    y: 613,
    w: 120,
    rot: 311,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 366,
    y: 537,
    w: 120,
    rot: 315,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 543,
    y: 516,
    w: 120,
    rot: 65,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 248,
    y: 516,
    w: 120,
    rot: 47,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 109,
    y: 514,
    w: 120,
    rot: 56,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Masa\nBass\n19770425",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/stone.png",
    x: 445,
    y: 446,
    w: 120,
    rot: 349,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 327,
    y: 423,
    w: 120,
    rot: 301,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Stone\nGuitar\n19751211",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 180,
    y: 417,
    w: 120,
    rot: 70,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 570,
    y: 399,
    w: 120,
    rot: 162,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 405,
    y: 332,
    w: 120,
    rot: 356,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 258,
    y: 325,
    w: 120,
    rot: 98,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 109,
    y: 320,
    w: 120,
    rot: 325,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ming\nDrum\n19730728",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 188,
    y: 228,
    w: 120,
    rot: 38,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Monster\nGuitar\n19761128",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 137,
    w: 120,
    rot: 341,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ashin\nVocal\n19751206",
    frameCornersOnly: true,
    frameSameDir: true,
  },
];

const page: PageConfig = {
  id: "page-01",
  toTraditional: true,
  inkBleedRadius: 1,
  right: {
    sections: [
      {
        text: "本次现场共采集纸质标本 5*5=25 件\n经交叉比对发现\n采集到的25件纸质标本在形态上可分为五类\n且每种形态分别对应特定的人物形象\n展现出明确的象征性功能\n\n经研究，该图案代表\nMONSTER\nSTONE\nMASA\nMING\nASHIN\n\n我？我不在上面ㄟ\n我在写野簿",
        options: {
          x: 42,
          y: 334 + 38 * 2,
          fontSize: 34,
          fontFamily: "ChenYuluoyan",
          color: COLOR_BLUE,
          wrapWidth: 600,
          lineHeight: 36,
        },
      },
    ],
  },
  spread: {
    photos: pile,
  },
  annotations: [createPageAnnotation("1")],
};

export default page;
