import type { PageConfig, SpreadPhotoLayout } from "../lib/types";

// Shape: Left page = open-top box; 40 face stickers fall in and pile up at the bottom.
// Right page: clean member ID column.
// Left pile calculated via Python pymunk simulation.

const pile: SpreadPhotoLayout[] = [
  {
    file: "resources/虾片/monster.png",
    x: 210,
    y: 900,
    w: 120,
    rot: 339,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 570,
    y: 900,
    w: 120,
    rot: 80,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 450,
    y: 900,
    w: 120,
    rot: 229,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 330,
    y: 900,
    w: 120,
    rot: 55,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 834,
    w: 120,
    rot: 156,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 270,
    y: 796,
    w: 120,
    rot: 315,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 570,
    y: 780,
    w: 120,
    rot: 84,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 452,
    y: 756,
    w: 120,
    rot: 294,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 169,
    y: 730,
    w: 120,
    rot: 158,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 345,
    y: 702,
    w: 120,
    rot: 353,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 567,
    y: 660,
    w: 120,
    rot: 178,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 244,
    y: 637,
    w: 120,
    rot: 304,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 449,
    y: 636,
    w: 120,
    rot: 195,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 626,
    w: 120,
    rot: 257,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 347,
    y: 574,
    w: 120,
    rot: 251,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 570,
    y: 540,
    w: 120,
    rot: 67,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 187,
    y: 532,
    w: 120,
    rot: 30,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Masa\nBass\n19770425",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/stone.png",
    x: 452,
    y: 516,
    w: 120,
    rot: 184,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 308,
    y: 460,
    w: 120,
    rot: 42,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Stone\nGuitar\n19751211",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 109,
    y: 440,
    w: 120,
    rot: 348,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 531,
    y: 426,
    w: 120,
    rot: 297,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 413,
    y: 403,
    w: 120,
    rot: 278,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Monster\nGuitar\n19761128",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ming.png",
    x: 215,
    y: 384,
    w: 120,
    rot: 264,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ming\nDrum\n19730728",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ashin.png",
    x: 321,
    y: 326,
    w: 120,
    rot: 200,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 114,
    y: 320,
    w: 120,
    rot: 303,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ashin\nVocal\n19751206",
    frameCornersOnly: true,
    frameSameDir: true,
  },
];

const feathers: SpreadPhotoLayout[] = [
  {
    file: "resources/虾片/feather_1.png",
    x: 1082,
    y: 50,
    w: 80,
    rot: 10,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 878,
    y: 50,
    w: 80,
    rot: 330,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 851,
    y: 50,
    w: 80,
    rot: 327,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1039,
    y: 50,
    w: 80,
    rot: 10,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 820,
    y: 57,
    w: 80,
    rot: 56,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 839,
    y: 111,
    w: 80,
    rot: 194,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 803,
    y: 135,
    w: 80,
    rot: 305,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1240,
    y: 153,
    w: 80,
    rot: 98,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1054,
    y: 185,
    w: 80,
    rot: 234,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1018,
    y: 208,
    w: 80,
    rot: 171,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1131,
    y: 237,
    w: 80,
    rot: 38,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 881,
    y: 263,
    w: 80,
    rot: 230,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 893,
    y: 286,
    w: 80,
    rot: 247,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1021,
    y: 312,
    w: 80,
    rot: 105,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 803,
    y: 319,
    w: 80,
    rot: 51,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1139,
    y: 332,
    w: 80,
    rot: 222,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 807,
    y: 356,
    w: 80,
    rot: 35,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1081,
    y: 356,
    w: 80,
    rot: 289,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 777,
    y: 372,
    w: 80,
    rot: 31,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 799,
    y: 422,
    w: 80,
    rot: 214,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 808,
    y: 446,
    w: 80,
    rot: 232,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 785,
    y: 478,
    w: 80,
    rot: 273,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1210,
    y: 500,
    w: 80,
    rot: 117,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1240,
    y: 518,
    w: 80,
    rot: 11,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1075,
    y: 526,
    w: 80,
    rot: 74,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1006,
    y: 537,
    w: 80,
    rot: 130,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1217,
    y: 565,
    w: 80,
    rot: 139,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 680,
    y: 593,
    w: 80,
    rot: 271,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1037,
    y: 594,
    w: 80,
    rot: 322,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 948,
    y: 604,
    w: 80,
    rot: 210,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 722,
    y: 625,
    w: 80,
    rot: 257,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 881,
    y: 632,
    w: 80,
    rot: 131,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 875,
    y: 655,
    w: 80,
    rot: 140,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1039,
    y: 722,
    w: 80,
    rot: 274,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 739,
    y: 790,
    w: 80,
    rot: 40,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 893,
    y: 877,
    w: 80,
    rot: 288,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 857,
    y: 893,
    w: 80,
    rot: 297,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 680,
    y: 897,
    w: 80,
    rot: 274,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1012,
    y: 903,
    w: 80,
    rot: 2,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 714,
    y: 912,
    w: 80,
    rot: 253,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1240,
    y: 926,
    w: 80,
    rot: 135,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1240,
    y: 964,
    w: 80,
    rot: 41,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1240,
    y: 989,
    w: 80,
    rot: 12,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1066,
    y: 995,
    w: 80,
    rot: 241,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1227,
    y: 1005,
    w: 80,
    rot: 72,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 723,
    y: 1050,
    w: 80,
    rot: 240,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 1240,
    y: 1050,
    w: 80,
    rot: 107,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 739,
    y: 1050,
    w: 80,
    rot: 192,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_2.png",
    x: 1097,
    y: 1050,
    w: 80,
    rot: 190,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/feather_1.png",
    x: 680,
    y: 1050,
    w: 80,
    rot: 266,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
];

const page: PageConfig = {
  id: "page-02",
  toTraditional: true,
  leftPhotos: [],
  rightSections: [],
  spreadPhotos: [...pile, ...feathers],
};

export default page;
