import type { PageConfig, SpreadPhotoLayout } from "../lib/types";
import { COLOR_DEFAULT } from "../lib/typography";

// Shape: Left page = dot matrix wavy tide.
// Right page: clean member ID column.
// Left pile calculated via Python pymunk simulation.

const pile: SpreadPhotoLayout[] = [
  {
    file: "resources/虾片/monster.png",
    x: 210,
    y: 900,
    w: 120,
    rot: 339,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 570,
    y: 900,
    w: 120,
    rot: 80,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 450,
    y: 900,
    w: 120,
    rot: 229,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 330,
    y: 900,
    w: 120,
    rot: 55,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 834,
    w: 120,
    rot: 156,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 270,
    y: 796,
    w: 120,
    rot: 315,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 570,
    y: 780,
    w: 120,
    rot: 84,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 452,
    y: 756,
    w: 120,
    rot: 294,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 169,
    y: 730,
    w: 120,
    rot: 158,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 345,
    y: 702,
    w: 120,
    rot: 353,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 567,
    y: 660,
    w: 120,
    rot: 178,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 244,
    y: 637,
    w: 120,
    rot: 304,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 449,
    y: 636,
    w: 120,
    rot: 195,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 109,
    y: 626,
    w: 120,
    rot: 257,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 347,
    y: 574,
    w: 120,
    rot: 251,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 570,
    y: 540,
    w: 120,
    rot: 67,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 187,
    y: 532,
    w: 120,
    rot: 30,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Masa\nBass\n19770425",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/stone.png",
    x: 452,
    y: 516,
    w: 120,
    rot: 184,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 308,
    y: 460,
    w: 120,
    rot: 42,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Stone\nGuitar\n19751211",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 109,
    y: 440,
    w: 120,
    rot: 348,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 531,
    y: 426,
    w: 120,
    rot: 297,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 413,
    y: 403,
    w: 120,
    rot: 278,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Monster\nGuitar\n19761128",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ming.png",
    x: 215,
    y: 384,
    w: 120,
    rot: 264,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ming\nDrum\n19730728",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ashin.png",
    x: 321,
    y: 326,
    w: 120,
    rot: 200,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 114,
    y: 320,
    w: 120,
    rot: 303,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ashin\nVocal\n19751206",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/hand_transparent.png",
    x: 1020,
    y: 820,
    w: 180,
    rot: -5,
    opacity: 0.9,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
];

const page: PageConfig = {
  id: "page-02",
  toTraditional: true,
  leftPhotos: [],
  rightSections: [
    {
      text: "现场采集到的纸质标本25件\n根据其形态特征可初步划分为五型\n推测其具有特定的象征性功用",
      options: {
        x: 42,
        y: 340,
        fontSize: 36,
        fontFamily: "ChenYuluoyan",
        color: COLOR_DEFAULT,
        wrapWidth: 600,
        lineHeight: 39,
      },
    },
  ],
  spreadPhotos: pile,
};

export default page;
