import type { PageConfig, SpreadPhotoLayout } from "../lib/types";
import { COLOR_BLUE, createPageAnnotation } from "../lib/typography";

const pile: SpreadPhotoLayout[] = [
  {
    file: "resources/虾片/ming.png",
    x: 318,
    y: 830,
    w: 120,
    rot: 21,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 566,
    y: 830,
    w: 120,
    rot: 80,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 114,
    y: 830,
    w: 120,
    rot: 155,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 438,
    y: 830,
    w: 120,
    rot: 205,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 224,
    y: 755,
    w: 120,
    rot: 348,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 502,
    y: 728,
    w: 120,
    rot: 323,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 382,
    y: 724,
    w: 120,
    rot: 236,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 113,
    y: 710,
    w: 120,
    rot: 49,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 288,
    y: 649,
    w: 120,
    rot: 105,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 566,
    y: 626,
    w: 120,
    rot: 158,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 446,
    y: 622,
    w: 120,
    rot: 9,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 176,
    y: 607,
    w: 120,
    rot: 338,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 352,
    y: 548,
    w: 120,
    rot: 299,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 566,
    y: 506,
    w: 120,
    rot: 94,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 239,
    y: 506,
    w: 120,
    rot: 174,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/masa.png",
    x: 113,
    y: 505,
    w: 120,
    rot: 42,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Masa\nBass\n19770425",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/stone.png",
    x: 449,
    y: 478,
    w: 120,
    rot: 284,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/stone.png",
    x: 340,
    y: 428,
    w: 120,
    rot: 319,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Stone\nGuitar\n19751211",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 178,
    y: 403,
    w: 120,
    rot: 65,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/monster.png",
    x: 562,
    y: 387,
    w: 120,
    rot: 125,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 320,
    y: 310,
    w: 120,
    rot: 110,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ming.png",
    x: 113,
    y: 301,
    w: 120,
    rot: 326,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ming\nDrum\n19730728",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/monster.png",
    x: 219,
    y: 245,
    w: 120,
    rot: 325,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Monster\nGuitar\n19761128",
    frameCornersOnly: true,
    frameSameDir: true,
  },
  {
    file: "resources/虾片/ashin.png",
    x: 338,
    y: 192,
    w: 120,
    rot: 235,
    showFrame: false,
    framePadX: 0,
    framePadY: 0,
    sublabel: "",
  },
  {
    file: "resources/虾片/ashin.png",
    x: 117,
    y: 182,
    w: 120,
    rot: 17,
    showFrame: true,
    framePadX: 0,
    framePadY: 0,
    sublabel: "Ashin\nVocal\n19751206",
    frameCornersOnly: true,
    frameSameDir: true,
  },
];

const page: PageConfig = {
  id: "page-01",
  toTraditional: true,
  inkBleedRadius: 1,
  right: {
    sections: [
      {
        text: "本次现场共采集纸质标本 5*5=25 件\n经交叉比对发现\n采集到的25件纸质标本在形态上可分为五类\n且每种形态分别对应特定的人物形象\n展现出明确的象征性功能\n\n经研究，该图案代表\nMONSTER\nSTONE\nMASA\nMING\nASHIN\n\n我？我不在上面ㄟ\n我在写野簿",
        options: {
          x: 42,
          y: 334 + 38 * 2,
          fontSize: 34,
          fontFamily: "ChenYuluoyan",
          color: COLOR_BLUE,
          wrapWidth: 600,
          lineHeight: 36,
        },
      },
    ],
  },
  spread: {
    photos: pile,
  },
  annotations: [createPageAnnotation("1")],
};

export default page;
